services:
  sandbox:
    build:
      context: .
      args:
        UID: 501
        GID: 20
    stdin_open: true
    tty: true
    volumes:
      - ./config/nvim:/home/dev/.config/nvim
      - ./config/.zshrc:/home/dev/.zshrc
      - ./config/bin:/home/dev/bin
      - nvim-data:/home/dev/.local/share/nvim
      - ./workspace:/workspace

volumes:
  nvim-data:
