services:
  sandbox:
    build:
      context: .
      args:
        UID: 501
        GID: 20
    stdin_open: true
    tty: true
    volumes:
      - ./config/nvim:/home/dev/.config/nvim
      - ./config/.zshrc:/home/dev/.zshrc
      - ./config/.gitconfig:/home/dev/.gitconfig
      - ./config/.tmux.conf:/home/dev/.tmux.conf
      - ./config/bin:/home/dev/bin
      - ./config/git:/home/dev/.config/git
      - nvim-data:/home/dev/.local/share/nvim
      - ./workspace:/sandbox

volumes:
  nvim-data:
