services:
  sandbox:
    build:
      context: .
      args:
        UID: 501
        GID: 20
    stdin_open: true
    tty: true
    volumes:
      - ~/.config:/home/dev/.config:ro
      - ~/.zshrc:/home/dev/.zshrc:ro
      - ~/bin:/home/dev/bin:ro
      - nvim-data:/home/dev/.local/share/nvim
      - ./workspace:/workspace

volumes:
  nvim-data:
